### ISSUE TITLE
Default user to run tests

### ISSUE THREAD

**Issue by davidCarlos** [shubhamshuklaer/ghi#3]
Hey @shubhamshuklaer ,  i started to take a look in your code. My first question is  if would not be better to create a default user, that all users that want to run our tests can use. I think this is more easy for the developer to run the tests. Maybe put the credentials of this user in a yml file, and make the helper.rb read from this yml. What do you think?

**Comment by shubhamshuklaer** [comment]
Its a good idea but I see a few problems
Even if the user is fake, it still linked to the creator and if we make username and password public someone can misuse it. For eg
    1. uploading bad things to that account
    2. run a script which will continuously keep making api request to it, forcing github people to suspend the account.
    3. changing the password(Just for causing problems).
    4. Using that account to post bad things everywhere(Other's repos) on github.

**Comment by shubhamshuklaer** [comment]
Even if we encrypt the username and password, it will be de-crypted before running tests, so anyone can write a test which will print it and run that test locally. So its essentially public.

**Comment by davidCarlos** [comment]
You are right. I will try to write some tests in the next days.
